// <auto-generated />
using EntityFrameworkEX.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFrameworkEX.Migrations
{
    [DbContext(typeof(EntityFrameworkEXContext))]
    [Migration("20211215175718_Newsale")]
    partial class Newsale
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityFrameworkEX.Models.Product", b =>
                {
                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SaleItemSalesName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProductName");

                    b.HasIndex("SaleItemSalesName");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("EntityFrameworkEX.Models.SaleItem", b =>
                {
                    b.Property<string>("SalesName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EndDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StartDate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SalesName");

                    b.ToTable("SaleItem");
                });

            modelBuilder.Entity("EntityFrameworkEX.Models.Product", b =>
                {
                    b.HasOne("EntityFrameworkEX.Models.SaleItem", null)
                        .WithMany("ProductName")
                        .HasForeignKey("SaleItemSalesName");
                });

            modelBuilder.Entity("EntityFrameworkEX.Models.SaleItem", b =>
                {
                    b.Navigation("ProductName");
                });
#pragma warning restore 612, 618
        }
    }
}
